"""empty message

Revision ID: 152b244f77fa
Revises: ce98766bfdec
Create Date: 2020-12-30 10:05:42.421755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152b244f77fa'
down_revision = 'ce98766bfdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
