"""empty message

Revision ID: 17c6c0d5377d
Revises: 9b09d8d691d3
Create Date: 2021-01-01 15:06:02.218350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c6c0d5377d'
down_revision = '9b09d8d691d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows')
    # ### end Alembic commands ###
