"""empty message

Revision ID: 2ef624a76b49
Revises: fb6cf6a2e517
Create Date: 2021-01-04 13:47:44.393075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef624a76b49'
down_revision = 'fb6cf6a2e517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_show_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'past_show_count')
    # ### end Alembic commands ###
