"""empty message

Revision ID: 50af054c4808
Revises: d3df385b40bf
Create Date: 2020-12-31 00:03:22.785367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50af054c4808'
down_revision = 'd3df385b40bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('Venue_id', sa.Integer(), nullable=False))
    op.add_column('Shows', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('Shows_venue_id_fkey', 'Shows', type_='foreignkey')
    op.create_foreign_key(None, 'Shows', 'Venue', ['Venue_id'], ['id'])
    op.drop_column('Shows', 'venue_id')
    op.drop_column('Shows', 'show_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('show_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Shows_show_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('Shows', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.create_foreign_key('Shows_venue_id_fkey', 'Shows', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Shows', 'id')
    op.drop_column('Shows', 'Venue_id')
    # ### end Alembic commands ###
