"""empty message

Revision ID: 729d44298687
Revises: 152b244f77fa
Create Date: 2020-12-30 13:36:21.312786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729d44298687'
down_revision = '152b244f77fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.String(), nullable=False))
    op.drop_column('shows', 'show_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
