"""empty message

Revision ID: 77f6a63d3489
Revises: 89726e2dc162
Create Date: 2021-01-05 18:33:10.474181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f6a63d3489'
down_revision = '89726e2dc162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.drop_column('Artist', 'upcoing_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('upcoing_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'upcoming_shows_count')
    # ### end Alembic commands ###
