"""empty message

Revision ID: 7da30306bb18
Revises: 4914c7df9ae4
Create Date: 2020-12-31 14:37:20.058228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da30306bb18'
down_revision = '4914c7df9ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.drop_column('Venue', 'upcoing_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoing_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'upcoming_shows_count')
    # ### end Alembic commands ###
