"""empty message

Revision ID: 89726e2dc162
Revises: 2ef624a76b49
Create Date: 2021-01-04 14:37:31.029934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89726e2dc162'
down_revision = '2ef624a76b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'name')
    # ### end Alembic commands ###
