"""empty message

Revision ID: 91975529ea36
Revises: cff1b1cadf5f
Create Date: 2020-12-31 13:48:54.808102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91975529ea36'
down_revision = 'cff1b1cadf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoing_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoing_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
