"""empty message

Revision ID: 9b09d8d691d3
Revises: 9c6f7257b52a
Create Date: 2021-01-01 15:05:45.760246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b09d8d691d3'
down_revision = '9c6f7257b52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
