"""empty message

Revision ID: 9c6f7257b52a
Revises: 0d9bbb848436
Create Date: 2021-01-01 11:53:53.238261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6f7257b52a'
down_revision = '0d9bbb848436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###
