"""empty message

Revision ID: c361d3b5ce19
Revises: eeeee68586f7
Create Date: 2020-12-31 15:14:45.094114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c361d3b5ce19'
down_revision = 'eeeee68586f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
