"""empty message

Revision ID: ce98766bfdec
Revises: fa57e1ae1ef2
Create Date: 2020-12-30 07:52:43.607566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce98766bfdec'
down_revision = 'fa57e1ae1ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genre', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.drop_constraint('Genre_Artist_id_fkey', 'Genre', type_='foreignkey')
    op.create_foreign_key(None, 'Genre', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Genre', 'Artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genre', sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    op.create_foreign_key('Genre_Artist_id_fkey', 'Genre', 'Artist', ['Artist_id'], ['id'])
    op.drop_column('Genre', 'artist_id')
    # ### end Alembic commands ###
