"""empty message

Revision ID: fa57e1ae1ef2
Revises: ff3c7c181d39
Create Date: 2020-12-30 07:39:08.739519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa57e1ae1ef2'
down_revision = 'ff3c7c181d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Genre', 'Artist', ['Artist_id'], ['id'])
    op.create_foreign_key(None, 'Genre', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    # ### end Alembic commands ###
