"""empty message

Revision ID: fb6cf6a2e517
Revises: 11dfc21a185f
Create Date: 2021-01-04 13:47:26.999605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6cf6a2e517'
down_revision = '11dfc21a185f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'past_show_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_show_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
